---
credentials:
  usernames:
    shix:
      email: "wanjiku.grace9@gmail.com"
      logged_in: False
      name: "Grace Wanjiku Wanjiru"
      password: "wanjiku123"

cookie:
  expiry_days: 0
  key: "cookie_signature_key"
  name: "cookie_name"

preauthorized:
  emails:
    - "wanjiku.grace9@gmail.com"
... 
  